name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            
            # Update repository
            cd /home/ubuntu/eduquest
            git pull origin main
            
            # Install system dependencies if needed
            sudo apt update
            sudo apt install -y nodejs npm
            
            # Install PM2 globally ONCE
            sudo npm install -g pm2
            
            # Deploy backend
            cd /home/ubuntu/eduquest/backend
            npm install
            pm2 restart db_server.js || pm2 start db_server.js
            pm2 restart canvas_server.js || pm2 start canvas_server.js

            # Create the .env file for React
            echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> .env
            echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> .env
            echo "REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }}" >> .env
            
            # Deploy frontend
            cd /home/ubuntu/eduquest/client
            npm install --force
                                    
            # Build the frontend
            npm run build
            
            # Start or restart the frontend
            pm2 restart frontend || pm2 start serve.js --name frontend
            
            # Save PM2 configuration so it persists after reboot
            pm2 save
